version: '3.8'

services:
  tunewalrus_backend:
    container_name: node_backend
    image: tunewalrus
    build:
      context: .
    ports:
      - 8080:80
    environment:
      - DB_HOST=127.0.0.1
      - DB_USER=postgres
      - DB_PASS=slime
    depends_on:
      - db
    restart: unless-stopped

  db:
    container_name: node_db
    image: postgres:12
    ports:
      - '5432:5432'
    volumes:
      - ./postgresdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/dbinit.sql
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=slime
      - POSTGRES_DB=tunewalrusdb
      - PGDATA=/var/lib/postgresql/data/some_name/

volumes:
  pgdata1: {}
